'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
fibSeq = [1, 2]
for i in range(10000000):
    if fibSeq[i] + fibSeq[i + 1] > 4000000:
        break
    else:
        fibSeq.append(fibSeq[i] + fibSeq[i + 1])
print(fibSeq)

total = 0
for i in range(len(fibSeq)):
    if fibSeq[i] % 2 == 0:
        total += fibSeq[i]
print(total)